name: Cucumber Report Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome version: $CHROME_VERSION"
          sudo apt-get install -y chromedriver

      - name: Verify Chrome and Chromedriver Installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run Gradle Build
        run: ./gradlew clean build

      - name: Run API Tests
        run: ./gradlew runApiTests
        continue-on-error: false

      - name: Run Web Tests 1
        run: ./gradlew runWebTests
        continue-on-error: false

      - name: Run Web Tests 2
        run: ./gradlew runWebTests2
        continue-on-error: false

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/
