name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission
        run: chmod +x

      - name: Run tests
        run: ./gradlew clean test

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            build/reports/api/
            build/reports/web/
