name: Pipeline Update

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test --info

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
            name: test-results
            path: build/test-results/test/

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
            name: junit-test-report
            path: build/reports/tests/test/


