name: Pipeline

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run API Tests
        run: ./gradlew testApi

      - name: Run Web Tests
        run: ./gradlew testWeb

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: build/reports/

      - name: Upload Web Test Report
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: build/reports/
