name: Pipeline

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run All Tests
        run: ./gradlew test --no-daemon --refresh-dependencies

      - name: Debug - List Reports Directory
        run: ls -R build/reports || true

      - name: Debug - List Test Results Directory
        run: ls -R build/test-results || true

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/**

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: build/reports/tests/testApi/**

      - name: Upload Web Test Report
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: build/reports/tests/testWeb/**

      - name: Upload Raw Test Results (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: raw-test-results
          path: build/test-results/**
