name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin'

      - name: Grant execute permission 
        run: chmod +x 

      - name: Run API Tests
        run: ./gradlew runApiTests

      - name: Run Web Tests
        run: ./gradlew runWebTests

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            build/reports/api/
            build/reports/web/
