name: Pipeline Update

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Check Test Report Directory
        run: ls -R build/cucumber-reports || echo "Cucumber reports not found"

      - name: Upload JUnit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: build/reports/


