name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: Run API tests
        run: ./gradlew runApiTests

      - name: Run Web tests
        run: ./gradlew runWebTests

      - name: Upload Tests Reports
        uses: actions/upload-artifact@v3
        with:
            name: tests-reports
            path: build/reports/tests/
            
